language: objective-c

before_install:
  - brew update
  - brew reinstall xctool

notifications:
  email: false

script:
  - xctool -project IconContacts.xcodeproj -scheme IconContacts -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean build